public class FontIndex {
  // Get the angle for the given direction.
  public static int Get(char input) {
    switch (input) {
      case '!':
        return 0;
      case '"':
        return 1;
      case '#':
        return 2;
      case '$':
        return 3;
      case '%':
        return 4;
      case '&':
        return 5;
      case '\'':
        return 6;
      case '(':
        return 7;
      case ')':
        return 8;
      case '*':
        return 9;
      case '+':
        return 10;
      case '-':
        return 11;
      case '/':
        return 12;
      case '0':
        return 13;
      case '1':
        return 14;
      case '2':
        return 15;
      case '3':
        return 16;
      case '4':
        return 17;
      case '5':
        return 18;
      case '6':
        return 19;
      case '7':
        return 20;
      case '8':
        return 21;
      case '9':
        return 22;
      case ':':
        return 23;
      case ';':
        return 24;
      case '<':
        return 25;
      case '=':
        return 26;
      case '>':
        return 27;
      case '?':
        return 28;
      case '@':
        return 29;
      case 'A':
        return 30;
      case 'B':
        return 31;
      case 'C':
        return 32;
      case 'D':
        return 33;
      case 'E':
        return 34;
      case 'F':
        return 35;
      case 'G':
        return 36;
      case 'H':
        return 37;
      case 'I':
        return 38;
      case 'J':
        return 39;
      case 'K':
        return 40;
      case 'L':
        return 41;
      case 'M':
        return 42;
      case 'N':
        return 43;
      case 'O':
        return 44;
      case 'P':
        return 45;
      case 'Q':
        return 46;
      case 'R':
        return 47;
      case 'S':
        return 48;
      case 'T':
        return 49;
      case 'U':
        return 50;
      case 'V':
        return 51;
      case 'W':
        return 52;
      case 'X':
        return 53;
      case 'Y':
        return 54;
      case 'Z':
        return 55;
      case '[':
        return 56;
      case '\\':
        return 57;
      case ']':
        return 58;
      case '^':
        return 59;
      case '`':
        return 60;
      case 'a':
        return 61;
      case 'b':
        return 62;
      case 'c':
        return 63;
      case 'd':
        return 64;
      case 'e':
        return 65;
      case 'f':
        return 66;
      case 'g':
        return 67;
      case 'h':
        return 68;
      case 'i':
        return 69;
      case 'j':
        return 70;
      case 'k':
        return 71;
      case 'l':
        return 72;
      case 'm':
        return 73;
      case 'n':
        return 74;
      case 'o':
        return 75;
      case 'p':
        return 76;
      case 'q':
        return 77;
      case 'r':
        return 78;
      case 's':
        return 79;
      case 't':
        return 80;
      case 'u':
        return 81;
      case 'v':
        return 82;
      case 'w':
        return 83;
      case 'x':
        return 84;
      case 'y':
        return 85;
      case 'z':
        return 86;
      case '{':
        return 87;
      case '|':
        return 88;
      case '}':
        return 89;
      case '~':
        return 90;
      case ',':
        return 91;
      case '.':
        return 92;
      case '_':
        return 93;
    }
    return 0;
  }
}
